name       = "bathysphere-read"
main       = "index.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "EVENTS"
id      = "c68aceb05a0e4c8bacda7cc2bafc829b"

# [[routes]]
# pattern = "bathysphere.tech/events"
# zone_name = "bathysphere.tech"
#
# [[routes]]
# pattern = "bathysphere.tech/stats"
# zone_name = "bathysphere.tech"